### ISSUE TITLE
There's a bug that switches the antilink system group setting with the welcome group setting 

### ISSUE THREAD

**Issue by Ryan-Zayne** [FantoX001/Miku-MD#10]

**Comment by Ryan-Zayne** [comment]
![Screenshot_20220813-141451](https://user-images.githubusercontent.com/93886198/184495788-f1cf9ee8-96c0-4207-ac49-74f430516dbf.png)


You'll see what I'm saying in this screenshot

**Comment by Ryan-Zayne** [comment]
As you can see the auto sticker function has the welcome function as well

**Comment by FantoX001** [comment]
Thanks for letting me know i will fox that bug as soon as possible. ☺
